# Generated by Django 2.2.3 on 2019-11-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(null=True, verbose_name='date joined')),
                ('registration_date', models.DateField(null=True, verbose_name='date registered')),
                ('name', models.CharField(max_length=128, verbose_name='user name')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
                ('is_guest', models.BooleanField(verbose_name='is guest user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='date registered')),
                ('action_id', models.CharField(choices=[(0, 'see the task'), (1, 'make solve submit (try to solve the task)'), (2, 'solve the task')], max_length=1, verbose_name='user action')),
                ('sended_to_clickhouse', models.BooleanField(default=False, verbose_name='delivered to clickhouse')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasksapp.Task', verbose_name='solving task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasksapp.Users', verbose_name='solver')),
            ],
        ),
    ]
